### ISSUE TITLE
Bang methods don't create persist-able state

### ISSUE THREAD

**Issue by danivovich** [flipsasser/maintain#2]
Should this test pass?  I feel like it should.  I'm not sure what is different about assignment vs the bang method, but it ends up not persisting to the database

```
    active_maintain_test = ActiveMaintainTest.new
    active_maintain_test.status = :bar
    active_maintain_test.save
    ActiveMaintainTest.first.status.should == :bar
    active_maintain_test.foo!
    active_maintain_test.save
    ActiveMaintainTest.first.status.should == :foo
```

Right now it fails on the second assertion

**Comment by flipsasser** [comment]
Interesting. I'll take a look!

**Comment by flipsasser** [comment]
Wow, I completely forgot to come back and let you know that this is fixed. There's also a new version of Maintain coming down the pike soon.

**Comment by flipsasser** [comment]
LULZ I forgot again. Daddy's on it.

**Comment by flipsasser** [comment]
ONE YEAR LATER THE THINGS ARE FIXED WHATUP THAT'S FREE SOFTWARE FOR YOU

I'm sorry
